"""update

Revision ID: 3ad5b7ef4772
Revises: d4e5f6a7b8c9
Create Date: 2026-04-05 10:54:39.495413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad5b7ef4772'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('bank_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('question_attributions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('question_attributions_question_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_question_attributions_question_id'))
        batch_op.create_index(batch_op.f('ix_question_attributions_question_id'), ['question_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_attributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_attributions_question_id'))
        batch_op.create_index(batch_op.f('ix_question_attributions_question_id'), ['question_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('question_attributions_question_id_key'), ['question_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('bank_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
